### ISSUE TITLE
2D transforms not working in IE11 / Windows 10

### ISSUE THREAD

**Issue by tdrsam** [IanLunn/Hover#71] opened 2015-09-03 03:44 UTC
I put a hover effect on the nav menu on my site and it works in Chrome & FF but not in IE. Just in case it makes a difference, I also have a CSS animation effect on another element, plus a jQuery animation effect which is on the same element as the CSS one, but it's a different element to the one the hover effect is on.

I tried adding the -ms- prefix to all the transform and animation attributes to all the lines of the hover CSS, so now they all have the basic transform or animation attribute as well as the webkit prefix and the -ms-prefix. I even tried putting them in the correct order (not that it matters) but it's not going.

Are there any known issues that could be causing this?

**Comment by IanLunn** [comment] 2015-09-03 06:25
There are no known issues. I have browser tested in IE so effects should work where the right properties are supported. Which effect(s) and version of IE are you seeing this in?

**Comment by tdrsam** [comment] 2015-09-03 06:31
I'm testing in IE11 and the effect is buzz-out.

**Comment by IanLunn** [comment] 2015-09-03 14:41
Can you check it works on the [official effects page](http://ianlunn.github.io/Hover/) please? Seems ok to me in IE11 Win7/8. If it's specific to your CSS, please post a reduce-test case.

**Comment by IanLunn** [comment] 2015-09-14 13:27
Closing as this works in my testing. Let me know if you're still having an issue.

**Comment by tdrsam** [comment] 2015-09-14 23:44
That's fine. I think it was some kind of clash with some functions I had. I don't need that webpage anymore, anyway.
 
Date: Mon, 14 Sep 2015 06:28:18 -0700

**Comment by tdrsam** [comment] 2015-09-16 06:03
I found the cause. User Agent Stylesheets. Which I fixed with a reset.css
 
Date: Mon, 14 Sep 2015 06:28:18 -0700

**Comment by gfdesign** [comment] 2016-07-01 20:50
Hi There
First of all, thank for this great resource but today when I start to use it, I realize it doesn't work in IE11 (and IE10)
Also, I've tested in the official page but it doesn't work as well.
Could you tell me what could be the problem and how to fix it?
Thanks

**Comment by IanLunn** [comment] 2016-07-02 21:51
Please provide operating system version and full version number for Internet Explorer.

**Comment by gfdesign** [comment] 2016-07-02 22:06
Hi Ian
I have W10 Pro with IE11.
Also, I've reviewed it using [Browserstack](https://www.browserstack.com) and I got the same results with W10, but when I test it using W8.1 on IE11 it works fine.
Therefore, it seems the problem comes from SO side.
Regards

**Comment by IanLunn** [comment] 2016-07-02 22:10
SO side? What is that? Are you using a touch-capable device?

**Comment by gfdesign** [comment] 2016-07-02 22:14
Sorry my English, I wanted to say OS (Operating System) :P

**Comment by IanLunn** [comment] 2016-07-02 22:24
Ok. I see the same issue in IE11 on Windows 10 via Browserstack. Will look into it.

**Comment by schwindyboo** [comment] 2016-07-26 11:35
Hi Ian,

Is there an update on this? I think your library is fantastic but I am experiencing the same as above (Win 10, IE11)

Thanks

Alex

**Comment by SaphuA** [comment] 2016-08-30 08:18
Like I mentioned in #102 this issue is fixed for me once I remove `transform: translateZ` from the css class. So I guess this has something to do with hardware acceleration? FYI: Disabling hardware acceleration doesn't do anything.

It also seems to be related to Win10 as others are mentioning. I tested it on Win7 and it works fine there.

**Comment by malreynolds** [comment] 2016-10-19 11:24
Can confirm experiencing same issue on Win10/IE11 combo and removing transform: translateZ fixes it.

**Comment by IanLunn** [comment] 2016-10-19 13:58
It looks as though the issue is actually the `backface-visibility: hidden` property. [Bug reported here](https://connect.microsoft.com/IE/Feedback/Details/2474735). I would recommend removing that property instead of `transform: translateZ(0)` so you can still get hardware acceleration.

I'll look into this further to see if a workaround can be added but it may mean making the library worse in all browsers to fix a few.

**Comment by IanLunn** [comment] 2016-10-21 13:54
This should now be working in IE 11 / Windows 10. I removed the `backface-visibility: hidden` property that improved font smoothing (weirdly) in Firefox and Chrome which was also the cause for the issue in IE 11.

**Closed by IanLunn** 2016-10-21 13:54 UTC
Labels: browser inconsistency
